### ISSUE TITLE
Tests are broken after update to `libxgboost`

### ISSUE THREAD

**Issue by rikhuijzer** [alan-turing-institute/MLJXGBoostInterface.jl#43]
I'm quickly opening this issue as a reminder for us. I'm currently already inside a fix inside a fix, so I'll just open this issue and focus on my main project for the day again.

The tests here are broken after the release of XGBoost 2.4 (https://github.com/dmlc/XGBoost.jl/pull/191). Came up in https://github.com/JuliaAI/MLJXGBoostInterface.jl/pull/42.

**Comment by tylerjthomas9** [comment]
I think the change to `hist` as the default tree method in libxgboost v2 is causing the test failures. Changing the default `tree_method="exact"` causes all the tests to pass. The histogram approach is just giving slightly worse performance on the test data. It is probably worth just bumping these thresholds for test failures.

**Comment by ExpandingMan** [comment]
Ah, I made a comment on the PR before I read this.  I'm a little surprised that they made a change to `libxgboost` that violated the tests since I surely believed my bounds were rather generous at the time, so I must say I feel slightly puzzled, however, as I said in my other comment, those bounds were surely set empirically based on no more than ~10 tests I did in my specific environment, so if everyone feels it's appropriate to loosen them I'm happy to go along with that.
